# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14-HynjEUg7NoWjtSnTvBZBTCS4MON7dO
"""

x = 2143

print("變數x的值是：",x)

print("變數x的記憶體地址是：",id(x))